class PriceTickerBar extends HTMLElement {
    connectedCallback() {
        this.attachShadow({ mode: 'open' });
        this.shadowRoot.innerHTML = `
            <style>
                :host {
                    display: block;
                    background: rgba(30, 41, 59, 0.95);
                    border-bottom: 1px solid rgba(255, 255, 255, 0.08);
                    overflow: hidden;
                    position: relative;
                    z-index: 99;
                }
                .ticker-container {
                    padding: 0.75rem 0;
                    position: relative;
                    overflow: hidden;
                }
                .ticker-track {
                    display: flex;
                    gap: 3rem;
                    animation: ticker-scroll 60s linear infinite;
                    white-space: nowrap;
                    min-width: max-content;
                }
                .ticker-item {
                    display: flex;
                    align-items: center;
                    gap: 0.5rem;
                    color: #cbd5e1;
                    font-family: 'Courier New', monospace;
                    font-weight: 500;
                }
                .pair {
                    color: #10b981;
                    font-weight: 600;
                }
                .price {
                    font-weight: 700;
                }
                .change {
                    padding: 0.125rem 0.5rem;
                    border-radius: 4px;
                    font-size: 0.875rem;
                    font-weight: 600;
                }
                .change.positive {
                    background: rgba(16, 185, 129, 0.2);
                    color: #10b981;
                }
                .change.negative {
                    background: rgba(239, 68, 68, 0.2);
                    color: #ef4444;
                }
                .ticker-label {
                    font-size: 0.75rem;
                    color: #94a3b8;
                    margin-left: 1rem;
                }
                @keyframes ticker-scroll {
                    0% {
                        transform: translateX(0);
                    }
                    100% {
                        transform: translateX(-50%);
                    }
                }
                .ticker-container:hover .ticker-track {
                    animation-play-state: paused;
                }
                @media (max-width: 768px) {
                    .ticker-track {
                        gap: 2rem;
                    }
                    .ticker-label {
                        display: none;
                    }
                }
            </style>
            <div class="ticker-container">
                <div class="ticker-track">
                    <!-- Ticker items will be generated by JavaScript -->
                </div>
            </div>
        `;
        
        this.initializeTicker();
    }
    
    initializeTicker() {
        const track = this.shadowRoot.querySelector('.ticker-track');
        
        // Sample forex pairs with simulated data
        const forexPairs = [
            { pair: 'EUR/USD', price: '1.08542', change: '+0.0012', changePercent: '+0.11%' },
            { pair: 'GBP/USD', price: '1.26785', change: '-0.0008', changePercent: '-0.06%' },
            { pair: 'USD/JPY', price: '147.892', change: '+0.423', changePercent: '+0.29%' },
            { pair: 'USD/CAD', price: '1.35421', change: '-0.0021', changePercent: '-0.15%' },
            { pair: 'AUD/USD', price: '0.65893', change: '+0.0015', changePercent: '+0.23%' },
            { pair: 'NZD/USD', price: '0.61245', change: '-0.0009', changePercent: '-0.15%' },
            { pair: 'USD/CHF', price: '0.87921', change: '+0.0011', changePercent: '+0.13%' },
            { pair: 'XAU/USD', price: '2034.56', change: '+12.34', changePercent: '+0.61%' },
            { pair: 'BTC/USD', price: '42876.5', change: '+856.3', changePercent: '+2.04%' },
            { pair: 'ETH/USD', price: '2274.82', change: '+42.18', changePercent: '+1.89%' }
        ];
        
        // Create ticker items (duplicate for seamless loop)
        const createTickerItems = () => {
            let itemsHTML = '';
            // Create 2 sets for seamless looping
            for (let i = 0; i < 2; i++) {
                forexPairs.forEach(pair => {
                    const isPositive = pair.change.startsWith('+');
                    itemsHTML += `
                        <div class="ticker-item">
                            <span class="pair">${pair.pair}</span>
                            <span class="price">${pair.price}</span>
                            <span class="change ${isPositive ? 'positive' : 'negative'}">
                                ${pair.change} (${pair.changePercent})
                            </span>
                            <span class="ticker-label">Delayed • Source: Free Forex API</span>
                        </div>
                    `;
                });
            }
            return itemsHTML;
        };
        
        track.innerHTML = createTickerItems();
        
        // Simulate price updates every 10 seconds
        setInterval(() => {
            this.updatePrices();
        }, 10000);
    }
    
    updatePrices() {
        const tickerItems = this.shadowRoot.querySelectorAll('.ticker-item');
        tickerItems.forEach(item => {
            const priceEl = item.querySelector('.price');
            const changeEl = item.querySelector('.change');
            
            if (priceEl && changeEl) {
                const currentPrice = parseFloat(priceEl.textContent);
                const randomChange = (Math.random() - 0.5) * 0.002; // Random small change
                const newPrice = currentPrice + (currentPrice * randomChange);
                
                // Format to appropriate decimal places
                let formattedPrice;
                if (priceEl.textContent.includes('.')) {
                    const decimalPlaces = priceEl.textContent.split('.')[1].length;
                    formattedPrice = newPrice.toFixed(decimalPlaces);
                } else {
                    formattedPrice = newPrice.toFixed(5);
                }
                
                const changeValue = newPrice - currentPrice;
                const changePercent = (changeValue / currentPrice * 100).toFixed(2);
                
                const isPositive = changeValue >= 0;
                const changeSign = isPositive ? '+' : '';
                
                priceEl.textContent = formattedPrice;
                changeEl.textContent = `${changeSign}${changeValue.toFixed(5)} (${changeSign}${changePercent}%)`;
                changeEl.className = `change ${isPositive ? 'positive' : 'negative'}`;
                
                // Add flash animation
                priceEl.style.color = isPositive ? '#10b981' : '#ef4444';
                setTimeout(() => {
                    priceEl.style.color = '';
                }, 1000);
            }
        });
    }
}

customElements.define('price-ticker-bar', PriceTickerBar);